// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  // use the schema in prisma/schema.prisma
  schema: "prisma/schema.prisma",

  // required for migrate in Prisma 7
 // but the actual connection is provided at runtime via the adapter
  datasource: {
    // do NOT resolve env at build time
    url: undefined,
  },
});
